In [ ]:
# 1. Create a numpy array of size 2 x 2
import numpy as np
array = np.array([[1, 2],[3, 4]])
print(array)

[[1 2]
 [3 4]]


In [ ]:
array = np.arange(0, 4).reshape(2, 2)
print(array)

[[0 1]
 [2 3]]


In [ ]:
# 2. Create a random numpy array of size 3 x 4
array = np.array([[4, 6, 5, 7],[3, 5, 6, 9],[1, 0, 9, 6]])
print(array)

[[4 6 5 7]
 [3 5 6 9]
 [1 0 9 6]]


In [ ]:
array = np.random.randint(0, 10, size=(3, 4))
print(array)

[[5 1 8 8]
 [3 2 8 6]
 [0 7 5 0]]


In [ ]:
# 3. Create a numpy array of ones and a numpy array of zeroes (ones)
array = np.array([[1,1,1,1],[1,1,1,1]])
print(array)

[[1 1 1 1]
 [1 1 1 1]]


In [ ]:
array = np.ones((2,4))
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 3. Create a numpy array of ones and a numpy of zeroes (zeroes)
array = np.array([[0,0,0,0],[0,0,0,0]])
print(array)

[[0 0 0 0]
 [0 0 0 0]]


In [ ]:
array = np.zeros((2, 4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 4. Create a random numpy array of size 6x3 and transpose it
array = np.array([[5,3,2],[2,8,0],[9,1,5],[8,0,4],[4,2,6],[0,9,3]])
print(array)

print()

transpose = array.T
print(transpose)

[[5 3 2]
 [2 8 0]
 [9 1 5]
 [8 0 4]
 [4 2 6]
 [0 9 3]]

[[5 2 9 8 4 0]
 [3 8 1 0 2 9]
 [2 0 5 4 6 3]]


In [ ]:
array = np.random.randint(0,9, size=(6, 3))
print(array)
print()
transpose = array.T
print(transpose)

[[7 4 3]
 [5 3 0]
 [6 3 1]
 [4 8 8]
 [7 6 7]
 [5 6 0]]

[[7 5 6 4 7 5]
 [4 3 3 8 6 6]
 [3 0 1 8 7 0]]


In [1]:
# 5. Create two random numpy array of size n x p and p x m and then compute the dot product
n, p = 2, 3
array = np.array([[2,5,6],[9,8,7],])
print(array)
print()
p, m = 3, 2
array2 = np.array([[2,3],[6,7],[9,0]])
print(array2)
print()
dot = np.dot(array, array2)
print(dot)

NameError: name 'np' is not defined

In [ ]:
n, p, m = 2, 3, 2

array = np.random.randint(0,9, size=(n, p))
array2 = np.random.randint(0,9, size=(p, m))

dot = np.dot(array, array2)
print(array)
print()
print(array2)
print()
print(dot)

[[5 2 0]
 [1 6 7]]

[[4 6]
 [5 7]
 [0 3]]

[[30 44]
 [34 69]]
